trigger:
  branches:
    include:
      - prod/frontend-azure-github

pool:
  vmImage: 'ubuntu-latest'

steps:
  # Установка Node.js
  - task: NodeTool@0
    inputs:
      versionSpec: '22.x'
    displayName: 'Install Node.js'

  # Установка зависимостей
  - script: npm install --legacy-peer-deps
    displayName: 'Install dependencies'

  # Сборка React-приложения
  - script: npm run build
    displayName: 'Build React app'

  # Сборка и пуш Docker-образа в ACR
  - task: Docker@2
    displayName: 'Build and push Docker image to ACR'
    inputs:
      containerRegistry: '$(acrServiceConnection)'
      repository: 'nginx'
      command: 'buildAndPush'
      Dockerfile: 'Dockerfile'
      tags: |
        $(Build.BuildId)
        latest
