from .auth_routes import auth_bp
from .payments_routes import payments_bp
from .iot_routes import iot_bp
from .user_routes import user_bp
from .home_routes import home_bp
from .sensor_routes import sensor_bp
from .default_security_mode_routes import default_security_mode_bp
from .general_user_notification_routes import general_notification_bp
from .security_user_notification_routes import security_notification_bp
from .subscription_plan_routes import subscription_plan_bp
from .mobile_devices_routes import mobile_device_bp
from .subscription_routes import subscription_bp
