from app.routes.auth_routes import auth_bp
from app.routes.user_profile_routes import user_profile_bp
from app.routes.payments_routes import payments_bp
from app.routes.mobile_devices_routes import mobile_device_bp
from app.routes.security_routes import security_bp
from app.routes.subscription_routes import subscription_bp
from app.routes.notification_history_routes import notification_bp
from app.routes.admin_routes import admin_bp
from app.routes.iot_routes import iot_bp