"""empty message

Revision ID: b8f188c7cbe9
Revises: fde10560ce1c
Create Date: 2025-11-27 23:51:55.067230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8f188c7cbe9'
down_revision = 'fde10560ce1c'
branch_labels = None
depends_on = None

sensor_type_enum = sa.Enum(
    'door',
    'motion',
    'camera',
    'smoke',
    name='sensor_type_enum'
)

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sensor_health_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sensor_id', sa.UUID(), nullable=False),
    sa.Column('battery_level', sa.Integer(), nullable=False),
    sa.Column('signal_strength', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('admin_audit_log',
    sa.Column('log_id', sa.UUID(), nullable=False),
    sa.Column('admin_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('method', sa.Enum('post', 'put', 'patch', 'delete', name='method_enum'), nullable=False),
    sa.Column('action_details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('log_id')
    )
    with op.batch_alter_table('admin_audit_log', schema=None) as batch_op:
        batch_op.create_index('idx_admin_audit_logs_admin_created', ['admin_id', 'created_at'], unique=False)
        batch_op.create_index('idx_admin_audit_logs_admin_id', ['admin_id'], unique=False)
        batch_op.create_index('idx_admin_audit_logs_created_at', ['created_at'], unique=False)

    with op.batch_alter_table('security_user_notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('severity_level', sa.Integer(), server_default='1', nullable=False))

    sensor_type_enum.create(op.get_bind(), checkfirst=True)

    with op.batch_alter_table('sensor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.alter_column(
            'type',
            existing_type=sa.String(length=50),
            type_=sensor_type_enum,
            nullable=False,
            postgresql_using="type::sensor_type_enum"
        )
        batch_op.drop_constraint('uq_sensor_short_id', type_='unique')
        batch_op.create_index(batch_op.f('ix_sensor_short_id'), ['short_id'], unique=True)

    with op.batch_alter_table('user_stats', schema=None) as batch_op:
        batch_op.create_index('idx_user_stats_date_user_count', ['stats_date', 'user_count'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_stats', schema=None) as batch_op:
        batch_op.drop_index('idx_user_stats_date_user_count')

    with op.batch_alter_table('sensor', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sensor_short_id'))
        batch_op.create_unique_constraint('uq_sensor_short_id', ['short_id'])
        batch_op.alter_column(
            'type',
            existing_type=sensor_type_enum,
            type_=sa.String(length=50),
            postgresql_using="type::text"
        )
        batch_op.drop_column('last_seen_at')

    sensor_type_enum.drop(op.get_bind(), checkfirst=True)

    with op.batch_alter_table('security_user_notifications', schema=None) as batch_op:
        batch_op.drop_column('severity_level')

    with op.batch_alter_table('admin_audit_log', schema=None) as batch_op:
        batch_op.drop_index('idx_admin_audit_logs_created_at')
        batch_op.drop_index('idx_admin_audit_logs_admin_id')
        batch_op.drop_index('idx_admin_audit_logs_admin_created')

    op.drop_table('admin_audit_log')
    op.drop_table('sensor_health_log')
    # ### end Alembic commands ###
