"""empty message

Revision ID: fb8bec36f477
Revises: bfaab0cb86d6
Create Date: 2025-05-21 17:18:57.468470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb8bec36f477'
down_revision = 'bfaab0cb86d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_stats',
    sa.Column('stats_id', sa.UUID(), nullable=False),
    sa.Column('stats_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('user_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('stats_id')
    )
    with op.batch_alter_table('user_stats', schema=None) as batch_op:
        batch_op.create_index('idx_user_stats_date', ['stats_date'], unique=False)

    op.create_table('subscription_plan_stats',
    sa.Column('stats_id', sa.UUID(), nullable=False),
    sa.Column('stats_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('user_count', sa.Integer(), nullable=False),
    sa.Column('avg_homes', sa.Float(), nullable=False),
    sa.Column('avg_sensors', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['subscription_plan.plan_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('stats_id')
    )
    with op.batch_alter_table('subscription_plan_stats', schema=None) as batch_op:
        batch_op.create_index('idx_subscription_plan_stats_date', ['stats_date'], unique=False)
        batch_op.create_index('idx_subscription_plan_stats_date_plan', ['stats_date', 'plan_id'], unique=False)
        batch_op.create_index('idx_subscription_plan_stats_plan', ['plan_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscription_plan_stats', schema=None) as batch_op:
        batch_op.drop_index('idx_subscription_plan_stats_plan')
        batch_op.drop_index('idx_subscription_plan_stats_date_plan')
        batch_op.drop_index('idx_subscription_plan_stats_date')

    op.drop_table('subscription_plan_stats')
    with op.batch_alter_table('user_stats', schema=None) as batch_op:
        batch_op.drop_index('idx_user_stats_date')

    op.drop_table('user_stats')
    # ### end Alembic commands ###
