name: Build and deploy Kotlin app to Azure Blob Storage

on:
  push:
    branches:
      - main
    paths:
      - 'mobile/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set Up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      - name: Change wrapper permissions
        run: chmod +x mobile/gradlew
        working-directory: ${{ github.workspace }}

      - name: Decode Keystore and Create File
        run: echo "${{ secrets.KEYSTORE_FILE }}" | base64 -d > mobile/release.jks
        working-directory: ${{ github.workspace }}
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

      - name: Build APK
        run: ./gradlew assembleRelease
        working-directory: mobile
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

      - name: Check build output
        run: ls -la mobile/app/build/outputs/apk/release/
        working-directory: mobile

      - name: Upload APK to Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: mobile/app/build/outputs/apk/release/app-release.apk

      - name: Upload to Azure Blob Storage
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az storage blob upload \
              --account-name safehomemobilestorage \
              --container-name apkfiles \
              --name app-release.apk \
              --file mobile/app/build/outputs/apk/release/app-release.apk \
              --auth-mode key \
              --account-key ${{ secrets.AZURE_STORAGE_KEY }} \
              --overwrite true
